language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: B7hBEmzo3//amfs+s1mGxihqfumboG6eYeqYfPHVNoXQtjy/tQqTY7bCjH0bjhcl/7+Co3SYgWYNcdJ258KSFA79grDXkRdKh7AMWLNQOklwRMXHOsr9SyRVA6gfO29SiBvhLr59ycSFOrBTV/g5J6+mjE+fEc1sWmSXO1Uz33hNwk3Ni9TnMSAdNCG2aCztXOnNycxUzCz+0zaZBrYyhQWU4PEjKb7Oy0uvNmo2tYlz8AapShIo3qjVUyH0bPoWfTsHvAHdV1jSxV/0SMIiQwc6ynWORPcWGN1uNmXGJ3CoZoOwy3xADExzfckq2ZWvh4tsmRd5eyGNcMcIrzM3p2EZJ7somWZG6DsbtNp9fXM00c2xM8mQbztQn0SARnm+PGzsaE7/KyDgYwdSoqLRFt4UfCOhEFEG4xzdcoj+DCqeyYjFOASRQsDBg7egFVNnvD9zF7Q8lzu1Di8lkGuL2BsVGNwsQp4eQkHDQJpCqqHC3LLMGOaYYCO6fyc/rdffmSA5uXudqmEK5+Xqci1vd58RE+UFGsadRzJGetHTrzkjekf1LwajDQTFYRsFZDHG8ywkd6EqBy7lqULI8zQXLfQ7oUlc/1WrcLPjQ78HTNOsDPXTKum3Zw2tdZ/KenECLiPZZTrUk1Bc74ssl54RV/cKfqYbsWcLuKPMgSdex2E=
  app: query-service
  on:
    repo: hittgv/Query-Service
