language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: L4QwpB/TnHAUjofxIJn3PB3bJ1sZelTTU8LhZU10cpIBsI2o1zAZJELeGqIAIvCayIOMboYJOqxaNU9BninQiIYGFZpDBa7Gtxo9UzPZo2wOz0koxY7Pv9mpCsvQZsCkJLaxTB7hvbU5pfD8ISpbZSR0B0ZT78fmF9U1un0A8DVL4YGZ27W8UTU9vtD2wWfGhIfyh48oHfllFVwT+ZjzwdU8846oARVmbdzW6b70PGE190pneedGLRkDPnf3QXrQYpZ9hzXcxEsD+YNhBFYpBiWOW/lte8i0ZcyPz8X8Vr0hNKpfEVWFAytD4/Uiv28ZFUfmG1JBfhJy4QRC44Su8bSjiKf6TeGvmIQrzGjH2Fj5A2Oi+s2oMVx8ng5JszrAV9cQG7nZCU2o8J36T0MijhifsFeMOzvVnjYXPsLN2U/Ouud5a2GUyPkSRf2v22nntVje4YKCb6U6pDDua1JwMcY322dEUSYG5HpuPxA6NZWpbYTptwNmIA2bOmd8/k5UiTFvUbMDAG3PChBQSofH26uyTcPH70CUrdxJmBN4yr9xFIi4x143yj3GdW55bvxlTlem7aiB31B2qyXdqGS50NkcyxqQ4wr9N55pd2zzbRnX39pWySKEeKJT4PSvWH8BfSYxF0VlDDnQRdri6p/CfYjSIL55rVExDJ2Cwd6VSBE=
  app: query-service
  on:
    repo: hittgv/Query-Service
